name: CI/CD

on: [push]

env:  
  NODE_VERSION: '10.x'

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - uses: actions/checkout@v1

    - name: Install
       run: |
          npm install
          npm run-script build -- --prod

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@3.2.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: deployment
        FOLDER: .